blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"